name: dotnet package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - name: Git Checkout
          uses: actions/checkout@v3
        - name: Setup .NET Core SDK 6
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.x.x'
        - name: Display dotnet version
          run: dotnet --version
        - name: Install dependencies
          run: dotnet restore
        - name: Test
          run: dotnet test -configuration Release
          
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build EmployeeManagement/EmployeeManagement.csproj
